export const ADD_CONSTRUCTOR_ITEM = 'ADD_CONSTRUCTOR_ITEM';
export const ADD_CONSTRUCTOR_BUN = 'ADD_CONSTRUCTOR_BUN';
export const DELETE_ITEM = 'DELETE_ITEM'
export const UPDATE_ON_ITEM_MOVE = 'UPDATE_ON_ITEM_MOVE';